version: '3.8'
name: mobilestore_docker
services:
  db:
    image: mysql:8.0.33
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=mobileStore
      - MYSQL_USER=KhoiVu
      - MYSQL_PASSWORD=Kh12.v3@C4b5rs6ft
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
  elasticsearch:
    image: elasticsearch:8.3.1
    container_name: elasticsearch
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      ELASTIC_PASSWORD: admin123
      xpack.security.enabled: true
    networks:
      - elk
  logstash:
     image: logstash:8.3.1
     container_name: logstash
     command: logstash -f /usr/share/logstash/pipeline/logstash.conf
     ports:
       - "9600:9600"
       - "5044:5044"
     volumes: 
       - ./logstash/logstash.yml:/usr/share/logstash/logstash.yml:ro,z
       - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
       - ./logs:/usr/share/logstash/logs:ro,z
     environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
     depends_on:
       - elasticsearch
     networks:
       - elk
  kibana:
     image: kibana:8.3.1
     container_name: kibana
     ports:
       - "5601:5601"
     environment:
       ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
       ELASTICSEARCH_USERNAME: kibana_system
       ELASTICSEARCH_PASSWORD: admin123
     depends_on:
       - elasticsearch
     networks:
       - elk
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: 'rabbitmq'
    ports:
        - "127.0.0.1:5672:5672"
        - "127.0.0.1:15672:15672"
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - elk
volumes:
  setup:
  elasticsearch:

networks:
  elk:
    driver: bridge